import Head from "next/head";
import { ReactElement, ReactNode } from "react";

type Props = {
  children: ReactNode;
  title: string;
};

export const Layout = ({ children, title }: Props): ReactElement => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};
