import { paths } from "@utils/paths";
import { useTranslation } from "next-i18next";
import Head from "next/head";
import Link from "next/link";
import { ReactElement, ReactNode } from "react";

type Props = {
  children: ReactNode;
  title: string;
};

export const Layout = ({ children, title }: Props): ReactElement => {
  const { t } = useTranslation();
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Link href={paths.signIn}>{t("Sign In")}</Link>
        <Link href={paths.signUp}>{t("Sign Up")}</Link>
      </nav>
      {children}
    </>
  );
};
