module.exports = {
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "../../tsconfig.json",
  },
  plugins: ["sort-keys-fix", "@typescript-eslint"],
  extends: [
    "turbo",
    "eslint:recommended",
    "plugin:import/typescript",
    "plugin:jsx-a11y/recommended",
    "plugin:promise/recommended",
    "plugin:react-hooks/recommended",
    "plugin:react/recommended",
    "next/core-web-vitals",
    "next",
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
  ],
  rules: {
    "@typescript-eslint/no-unused-vars": ["error"],
    "no-await-in-loop": "error",
    "no-constant-binary-expression": "error",
    "no-duplicate-imports": "error",
    "no-self-compare": "error",
    "no-use-before-define": "error",
    "no-cond-assign": "error",
    "no-constant-condition": "error",
    "no-unreachable": "error",
    "no-unused-expressions": "error",
    "no-sequences": "error",
    curly: "error",
    eqeqeq: ["error", "smart"],
    "max-params": ["error", 3],
    "no-console": "warn",
    "no-lonely-if": "error",
    "no-unneeded-ternary": "error",
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "require-await": "error",
    "sort-keys-fix/sort-keys-fix": "warn",
    "@typescript-eslint/array-type": "error",
    "@typescript-eslint/consistent-type-definitions": ["error", "type"],
    "@typescript-eslint/no-unused-expressions": [
      "error",
      {
        enforceForJSX: true,
      },
    ],
    "tailwindcss/no-custom-classname": "off",
    "prettier/prettier": "error",
    "jsx-a11y/label-has-associated-control": "off",
    "@next/next/no-html-link-for-pages": "off",
  },
};
